//
//  Field.swift
//  MRZ
//
//  Created by Игорь Клещёв on 12.05.15.
//  Copyright (c) 2015 Regula Forensics. All rights reserved.
//

import Foundation

struct TextField {
    let name: String
    let value: String?
    let status: Int
}

enum FieldTypes: Int {
    case     ft_Document_Class_Code = 0
    case     ft_Issuing_State_Code = 1
    case     ft_Document_Number = 2
    case     ft_Date_of_Expiry = 3
    case     ft_Date_of_Issue = 4
    case     ft_Date_of_Birth = 5
    case     ft_Place_of_Birth = 6
    case     ft_Personal_Number = 7
    case     ft_Surname = 8
    case     ft_Given_Names = 9
    case     ft_Mothers_Name = 10
    case     ft_Nationality = 11
    case     ft_Sex = 12
    case     ft_Height = 13
    case     ft_Weight = 14
    case     ft_Eyes_Color = 15
    case     ft_Hair_Color = 16
    case     ft_Address = 17
    case     ft_Donor = 18
    case     ft_Social_Security_Number = 19
    case     ft_DL_Class = 20
    case     ft_DL_Endorsed = 21
    case     ft_DL_Restriction_Code = 22
    case     ft_DL_Under_21_Date = 23
    case     ft_Authority = 24
    case     ft_Surname_And_Given_Names = 25
    case     ft_Nationality_Code = 26
    case     ft_Passport_Number = 27
    case     ft_Invitation_Number = 28
    case     ft_Visa_ID = 29
    case     ft_Visa_Class = 30
    case     ft_Visa_SubClass = 31
    case     ft_MRZ_String1 = 32
    case     ft_MRZ_String2 = 33
    case     ft_MRZ_String3 = 34
    case     ft_MRZ_Type = 35
    case     ft_Optional_Data = 36
    case     ft_Document_Class_Name = 37
    case     ft_Issuing_State_Name = 38
    case     ft_Place_of_Issue = 39
    case     ft_Document_Number_Checksum = 40
    case     ft_Date_of_Birth_Checksum = 41
    case     ft_Date_of_Expiry_Checksum = 42
    case     ft_Personal_Number_Checksum = 43
    case     ft_FinalChecksum = 44
    case     ft_Passport_Number_Checksum = 45
    case     ft_Invitation_Number_Checksum = 46
    case     ft_Visa_ID_Checksum = 47
    case     ft_Surname_And_Given_Names_Checksum = 48
    case     ft_Visa_Valid_Until_Checksum = 49
    case     ft_Other = 50
    case     ft_MRZ_Strings = 51
    case     ft_Name_Suffix = 52
    case     ft_Name_Prefix = 53
    case     ft_Date_of_Issue_Checksum = 54
    case     ft_Date_of_Issue_CheckDigit = 55
    case     ft_Document_Series = 56
    case     ft_RegCert_RegNumber = 57
    case     ft_RegCert_CarModel = 58
    case     ft_RegCert_CarColor = 59
    case     ft_RegCert_BodyNumber = 60
    case     ft_RegCert_CarType = 61
    case     ft_RegCert_MaxWeight = 62
    case     ft_Reg_Cert_Weight = 63
    case     ft_Address_Area = 64
    case     ft_Address_State = 65
    case     ft_Address_Building = 66
    case     ft_Address_House = 67
    case     ft_Address_Flat = 68
    case     ft_Place_of_Registration = 69
    case     ft_Date_of_Registration = 70
    case     ft_Resident_From = 71
    case     ft_Resident_Until = 72
    case     ft_Authority_Code = 73
    case     ft_Place_of_Birth_Area = 74
    case     ft_Place_of_Birth_StateCode = 75
    case     ft_Address_Street = 76
    case     ft_Address_City = 77
    case     ft_Address_Jurisdiction_Code = 78
    case     ft_Address_Postal_Code = 79
    case     ft_Document_Number_CheckDigit = 80
    case     ft_Date_of_Birth_CheckDigit = 81
    case     ft_Date_of_Expiry_CheckDigit = 82
    case     ft_Personal_Number_CheckDigit = 83
    case     ft_FinalCheckDigit = 84
    case     ft_Passport_Number_CheckDigit = 85
    case     ft_Invitation_Number_CheckDigit = 86
    case     ft_Visa_ID_CheckDigit = 87
    case     ft_Surname_And_Given_Names_CheckDigit = 88
    case     ft_Visa_Valid_Until_CheckDigit = 89
    case     ft_Permit_DL_Class = 90
    case     ft_Permit_Date_of_Expiry = 91
    case     ft_Permit_Identifier = 92
    case     ft_Permit_Date_of_Issue = 93
    case     ft_Permit_Restriction_Code = 94
    case     ft_Permit_Endorsed = 95
    case     ft_Issue_Timestamp = 96
    case     ft_Number_of_Duplicates = 97
    case     ft_Medical_Indicator_Codes = 98
    case     ft_Non_Resident_Indicator = 99
    case     ft_Visa_Type = 100
    case     ft_Visa_Valid_From = 101
    case     ft_Visa_Valid_Until = 102
    case     ft_Duration_of_Stay = 103
    case     ft_Number_of_Entries = 104
    case     ft_Day = 105
    case     ft_Month = 106
    case     ft_Year = 107
    case     ft_Unique_Customer_Identifier = 108
    case     ft_Commercial_Vehicle_Codes = 109
    case     ft_AKA_Date_of_Birth = 110
    case     ft_AKA_Social_Security_Number = 111
    case     ft_AKA_Surname = 112
    case     ft_AKA_Given_Names = 113
    case     ft_AKA_Name_Suffix = 114
    case     ft_AKA_Name_Prefix = 115
    case     ft_Mailing_Address_Street = 116
    case     ft_Mailing_Address_City = 117
    case     ft_Mailing_Address_Jurisdiction_Code = 118
    case     ft_Mailing_Address_Postal_Code = 119
    case     ft_Audit_Information = 120
    case     ft_Inventory_Number = 121
    case     ft_Race_Ethnicity = 122
    case     ft_Jurisdiction_Vehicle_Class = 123
    case     ft_Jurisdiction_Endorsement_Code = 124
    case     ft_Jurisdiction_Restriction_Code = 125
    case     ft_Family_Name = 126
    case     ft_Given_Names_RUS = 127
    case     ft_Visa_ID_RUS = 128
    case     ft_Fathers_Name = 129
    case     ft_Fathers_Name_RUS = 130
    case     ft_Surname_And_Given_Names_RUS = 131
    case     ft_Place_Of_Birth_RUS = 132
    case     ft_Authority_RUS = 133
    case     ft_Issuing_State_Code_Numeric = 134
    case     ft_Nationality_Code_Numeric = 135
    case     ft_Engine_Power = 136
    case     ft_Engine_Volume = 137
    case     ft_Chassis_Number = 138
    case     ft_Engine_Number = 139
    case     ft_Engine_Model = 140
    case     ft_Vehicle_Category = 141
    case     ft_Identity_Card_Number = 142
    case     ft_Control_No = 143
    case     ft_Parrent_s_Given_Names = 144
    case     ft_Second_Surname = 145
    case     ft_Middle_Name = 146
    case     ft_RegCert_VIN = 147
    case     ft_RegCert_VIN_CheckDigit = 148
    case     ft_RegCert_VIN_Checksum = 149
    case     ft_Line1_CheckDigit = 150
    case     ft_Line2_CheckDigit = 151
    case     ft_Line3_CheckDigit = 152
    case     ft_Line1_Checksum = 153
    case     ft_Line2_Checksum = 154
    case     ft_Line3_Checksum = 155
    case     ft_RegCert_RegNumber_CheckDigit = 156
    case     ft_RegCert_RegNumber_Checksum = 157
    case     ft_RegCert_Vehicle_ITS_Code = 158
    case     ft_Card_Access_Number = 159
    case     ft_Marital_Status = 160
    case     ft_Company_Name = 161
    case     ft_Special_Notes = 162
    case     ft_Surname_of_Spose = 163
    case     ft_Tracking_Number = 164
    case     ft_Booklet_Number = 165
    case     ft_Children = 166
    case     ft_Copy = 167
    case     ft_Serial_Number = 168
    case     ft_Dossier_Number = 169
    case     ft_AKA_Surname_And_Given_Names = 170
    case     ft_Territorial_Validity = 171
    case     ft_MRZ_Strings_With_Correct_CheckSums = 172
    case     ft_DL_CDL_Restriction_Code = 173
    case     ft_DL_Under_18_Date = 174
    case     ft_DL_Record_Created = 175
    case     ft_DL_Duplicate_Date = 176
    case     ft_DL_Iss_Type = 177
    case     ft_Military_Book_Number = 178
    case     ft_Destination = 179
    case     ft_Blood_Group = 180
    case     ft_Sequence_Number = 181
    case     ft_RegCert_BodyType = 182
    case     ft_RegCert_CarMark = 183
    case     ft_Transaction_Number = 184
    case     ft_Age = 185
    case     ft_Folio_Number = 186
    case     ft_Voter_Key = 187
    case     ft_Address_Municipality = 188
    case     ft_Address_Location = 189
    case     ft_Section = 190
    case     ft_OCR_Number = 191
    case     ft_Federal_Elections = 192
    case     ft_Reference_Number = 193
    case     ft_Optional_Data_Checksum = 194
    case     ft_Optional_Data_CheckDigit = 195
    case     ft_Visa_Number = 196
    case     ft_Visa_Number_Checksum = 197
    case     ft_Visa_Number_CheckDigit = 198
    case     ft_Voter = 199
    case     ft_Previous_Type = 200
    case     ft_FieldFromMRZ = 220
    case     ft_CurrentDate = 221
    case     ft_Status_Date_of_Expiry = 251
    case     ft_Banknote_Number = 252
    case     ft_CSC_Code = 253
    case     ft_Artistic_Name = 254
    case     ft_Academic_Title = 255
    case     ft_Address_Country = 256
    case     ft_Address_Zipcode = 257
    case     ft_eID_Residence_Permit1 = 258
    case     ft_eID_Residence_Permit2 = 259
    case     ft_eID_PlaceOfBirth_Street = 260
    case     ft_eID_PlaceOfBirth_City = 261
    case     ft_eID_PlaceOfBirth_State = 262
    case     ft_eID_PlaceOfBirth_Country = 263
    case     ft_eID_PlaceOfBirth_Zipcode = 264
    case     ft_CDL_Class = 265
    case     ft_DL_Under_19_Date = 266
    case     ft_Weight_pounds = 267
    case     ft_Limited_Duration_Document_Indicator = 268
    case     ft_Endorsement_Expiration_Date = 269
    case     ft_Revision_Date = 270
    case     ft_Compliance_Type = 271
    case     ft_Family_name_truncation = 272
    case     ft_First_name_truncation = 273
    case     ft_Middle_name_truncation = 274
    case     ft_Exam_Date = 275
    case     ft_Organization = 276
    case     ft_Department = 277
    case     ft_Pay_Grade = 278
    case     ft_Rank = 279
    case     ft_Benefits_Number = 280
    case     ft_Sponsor_Service = 281
    case     ft_Sponsor_Status = 282
    case     ft_Sponsor = 283
    case     ft_Relationship = 284
    case     ft_USCIS = 285
    case     ft_Category = 286
    case     ft_Conditions = 287
    case     ft_Identifier = 288
    case     ft_Configuration = 289
    case     ft_Discretionary_data = 290
    case     ft_Line1_Optional_Data = 291
    case     ft_Line2_Optional_Data = 292
    case     ft_Line3_Optional_Data = 293
    case     ft_EQV_Code = 294
    case     ft_ALT_Code = 295
    case     ft_Binary_Code = 296
    case     ft_Pseudo_Code = 297
    case     ft_Fee = 298
    case     ft_Stamp_Number = 299
    case     ft_GNIB_Number = 340
    case     ft_Dept_Number = 341
    case     ft_Telex_Code = 342
    case     ft_Allergies = 343
    case     ft_Sp_Code = 344
    case     ft_Court_Code = 345
    case     ft_Cty = 346
    case     ft_Sponsor_SSN = 347
    case     ft_DoD_Number = 348
    case     ft_MC_Novice_Date = 349
    case     ft_DUF_Number = 350
    case     ft_AGY = 351
    case     ft_PNR_Code = 352
    case     ft_From_Airport_Code = 353
    case     ft_To_Airport_Code = 354
    case     ft_Flight_Number = 355
    case     ft_Date_of_Flight = 356
    case     ft_Seat_Number = 357
    case     ft_Date_of_Issue_Boarding_Pass = 358
    case     ft_CCW_Until = 359
    case     ft_Reference_Number_Checksum = 360
    case     ft_Reference_Number_CheckDigit = 361
    case     ft_Room_Number = 362
    case     ft_Religion = 363
    case     ft_RemainderTerm = 364
    case     ft_Electronic_Ticket_Indicator = 365
    case     ft_Compartment_Code = 366
    case     ft_CheckIn_Sequence_Number = 367
    case     ft_Airline_Designator_of_boarding_pass_issuer = 368
    case     ft_Airline_Numeric_Code = 369
    case     ft_Ticket_Number = 370
    case     ft_Frequent_Flyer_Airline_Designator = 371
    case     ft_Frequent_Flyer_Number = 372
    case     ft_Free_Baggage_Allowance = 373
    case     ft_PDF417Codec = 374
    case     ft_Identity_Card_Number_Checksum = 375
    case     ft_Identity_Card_Number_CheckDigit = 376
    case     ft_Veteran = 377
    case     ft_DLClassCode_A1_From = 378
    case     ft_DLClassCode_A1_To = 379
    case     ft_DLClassCode_A1_Notes = 380
    case     ft_DLClassCode_A_From = 381
    case     ft_DLClassCode_A_To = 382
    case     ft_DLClassCode_A_Notes = 383
    case     ft_DLClassCode_B_From = 384
    case     ft_DLClassCode_B_To = 385
    case     ft_DLClassCode_B_Notes = 386
    case     ft_DLClassCode_C1_From = 387
    case     ft_DLClassCode_C1_To = 388
    case     ft_DLClassCode_C1_Notes = 389
    case     ft_DLClassCode_C_From = 390
    case     ft_DLClassCode_C_To = 391
    case     ft_DLClassCode_C_Notes = 392
    case     ft_DLClassCode_D1_From = 393
    case     ft_DLClassCode_D1_To = 394
    case     ft_DLClassCode_D1_Notes = 395
    case     ft_DLClassCode_D_From = 396
    case     ft_DLClassCode_D_To = 397
    case     ft_DLClassCode_D_Notes = 398
    case     ft_DLClassCode_BE_From = 399
    case     ft_DLClassCode_BE_To = 400
    case     ft_DLClassCode_BE_Notes = 401
    case     ft_DLClassCode_C1E_From = 402
    case     ft_DLClassCode_C1E_To = 403
    case     ft_DLClassCode_C1E_Notes = 404
    case     ft_DLClassCode_CE_From = 405
    case     ft_DLClassCode_CE_To = 406
    case     ft_DLClassCode_CE_Notes = 407
    case     ft_DLClassCode_D1E_From = 408
    case     ft_DLClassCode_D1E_To = 409
    case     ft_DLClassCode_D1E_Notes = 410
    case     ft_DLClassCode_DE_From = 411
    case     ft_DLClassCode_DE_To = 412
    case     ft_DLClassCode_DE_Notes = 413
    case     ft_DLClassCode_M_From = 414
    case     ft_DLClassCode_M_To = 415
    case     ft_DLClassCode_M_Notes = 416
    case     ft_DLClassCode_L_From = 417
    case     ft_DLClassCode_L_To = 418
    case     ft_DLClassCode_L_Notes = 419
    case     ft_DLClassCode_T_From = 420
    case     ft_DLClassCode_T_To = 421
    case     ft_DLClassCode_T_Notes = 422
    case     ft_DLClassCode_AM_From = 423
    case     ft_DLClassCode_AM_To = 424
    case     ft_DLClassCode_AM_Notes = 425
    case     ft_DLClassCode_A2_From = 426
    case     ft_DLClassCode_A2_To = 427
    case     ft_DLClassCode_A2_Notes = 428
    case     ft_DLClassCode_B1_From = 429
    case     ft_DLClassCode_B1_To = 430
    case     ft_DLClassCode_B1_Notes = 431
    case     ft_Surname_at_Birth = 432
    case     ft_Civil_Status = 433
    case     ft_Number_of_Seats = 434
    case     ft_Number_of_Standing_Places = 435
    case     ft_Max_Speed = 436
    case     ft_Fuel_Type = 437
    case     ft_EC_Environmental_Type = 438
    case     ft_Power_Weight_Ratio = 439
    case     ft_Max_Mass_of_Trailer_Braked = 440
    case     ft_Max_Mass_of_Trailer_Unbraked = 441
    case     ft_Transmission_Type = 442
    case     ft_Trailer_Hitch = 443
    case     ft_Accompanied_by = 444
    case     ft_Police_District = 445
    case     ft_First_Issue_Date = 446
    case     ft_Payload_Capacity = 447
    case     ft_Number_of_Axels = 448
    case     ft_Permissible_Axle_Load = 449
    case     ft_Precinct = 450
    case     ft_Invited_by = 451
    case     ft_Purpose_of_Entry = 452
    case     ft_Skin_Color = 453
    case     ft_Complexion = 454
    case     ft_Airport_From = 455
    case     ft_Airport_To = 456
    case     ft_Airline_Name = 457
    case     ft_Airline_Name_Frequent_Flyer = 458
    case     ft_In_Tanks = 460
    case     ft_Exept_In_Tanks = 461
}

class FieldHelper {
    
    static func fieldNameByType(fieldType: FieldTypes) -> String{
        var text: String!
        switch(fieldType){
        case FieldTypes.ft_Document_Class_Code: text = "Document Class Code"
        case FieldTypes.ft_Issuing_State_Code: text = "Issuing State Code"
        case FieldTypes.ft_Document_Number: text = "Document Number"
        case FieldTypes.ft_Date_of_Expiry: text = "Date of Expiry"
        case FieldTypes.ft_Date_of_Issue: text = "Date of Issue"
        case FieldTypes.ft_Date_of_Birth: text = "Date of Birth"
        case FieldTypes.ft_Place_of_Birth: text = "Place of Birth"
        case FieldTypes.ft_Personal_Number: text = "Personal Number"
        case FieldTypes.ft_Surname: text = "Surname"
        case FieldTypes.ft_Given_Names: text = "Given Names"
        case FieldTypes.ft_Mothers_Name: text = "Mothers Name"
        case FieldTypes.ft_Nationality: text = "Nationality"
        case FieldTypes.ft_Sex: text = "Sex"
        case FieldTypes.ft_Height: text = "Height"
        case FieldTypes.ft_Weight: text = "Weight"
        case FieldTypes.ft_Eyes_Color: text = "Eyes Color"
        case FieldTypes.ft_Hair_Color: text = "Hair Color"
        case FieldTypes.ft_Address: text = "Address"
        case FieldTypes.ft_Donor: text = "Donor"
        case FieldTypes.ft_Social_Security_Number: text = "Social Security Number"
        case FieldTypes.ft_DL_Class: text = "DL Class"
        case FieldTypes.ft_DL_Endorsed: text = "DL Endorsed"
        case FieldTypes.ft_DL_Restriction_Code: text = "DL Restriction Code"
        case FieldTypes.ft_DL_Under_21_Date: text = "DL Under 21 Date"
        case FieldTypes.ft_Authority: text = "Authority"
        case FieldTypes.ft_Surname_And_Given_Names: text = "Surname And Given Names"
        case FieldTypes.ft_Nationality_Code: text = "Nationality Code"
        case FieldTypes.ft_Passport_Number: text = "Passport Number"
        case FieldTypes.ft_Invitation_Number: text = "Invitation Number"
        case FieldTypes.ft_Visa_ID: text = "Visa ID"
        case FieldTypes.ft_Visa_Class: text = "Visa Class"
        case FieldTypes.ft_Visa_SubClass: text = "Visa SubClass"
        case FieldTypes.ft_MRZ_String1: text = "MRZ String1"
        case FieldTypes.ft_MRZ_String2: text = "MRZ String2"
        case FieldTypes.ft_MRZ_String3: text = "MRZ String3"
        case FieldTypes.ft_MRZ_Type: text = "MRZ Type"
        case FieldTypes.ft_Optional_Data: text = "Optional Data"
        case FieldTypes.ft_Document_Class_Name: text = "Document Class Name"
        case FieldTypes.ft_Issuing_State_Name: text = "Issuing State Name"
        case FieldTypes.ft_Place_of_Issue: text = "Place of Issue"
        case FieldTypes.ft_Document_Number_Checksum: text = "Document Number Checksum"
        case FieldTypes.ft_Date_of_Birth_Checksum: text = "Date of Birth Checksum"
        case FieldTypes.ft_Date_of_Expiry_Checksum: text = "Date of Expiry Checksum"
        case FieldTypes.ft_Personal_Number_Checksum: text = "Personal Number Checksum"
        case FieldTypes.ft_FinalChecksum: text = "Final Checksum"
        case FieldTypes.ft_Passport_Number_Checksum: text = "Passport Number Checksum"
        case FieldTypes.ft_Invitation_Number_Checksum: text = "Invitation Number Checksum"
        case FieldTypes.ft_Visa_ID_Checksum: text = "Visa ID Checksum"
        case FieldTypes.ft_Surname_And_Given_Names_Checksum: text = "Surname And Given Names Checksum"
        case FieldTypes.ft_Visa_Valid_Until_Checksum: text = "Visa Valid Until Checksum"
        case FieldTypes.ft_Other: text = "Other"
        case FieldTypes.ft_MRZ_Strings: text = "MRZ Strings"
        case FieldTypes.ft_Name_Suffix: text = "Name Suffix"
        case FieldTypes.ft_Name_Prefix: text = "Name Prefix"
        case FieldTypes.ft_Date_of_Issue_Checksum: text = "Date of Issue Checksum"
        case FieldTypes.ft_Date_of_Issue_CheckDigit: text = "Date of Issue CheckDigit"
        case FieldTypes.ft_Document_Series: text = "Document Series"
        case FieldTypes.ft_RegCert_RegNumber: text = "RegCert RegNumber"
        case FieldTypes.ft_RegCert_CarModel: text = "RegCert CarModel"
        case FieldTypes.ft_RegCert_CarColor: text = "RegCert CarColor"
        case FieldTypes.ft_RegCert_BodyNumber: text = "RegCert BodyNumber"
        case FieldTypes.ft_RegCert_CarType: text = "RegCert CarType"
        case FieldTypes.ft_RegCert_MaxWeight: text = "RegCert MaxWeight"
        case FieldTypes.ft_Reg_Cert_Weight: text = "Reg Cert Weight"
        case FieldTypes.ft_Address_Area: text = "Address Area"
        case FieldTypes.ft_Address_State: text = "Address State"
        case FieldTypes.ft_Address_Building: text = "Address Building"
        case FieldTypes.ft_Address_House: text = "Address House"
        case FieldTypes.ft_Address_Flat: text = "Address Flat"
        case FieldTypes.ft_Place_of_Registration: text = "Place of Registration"
        case FieldTypes.ft_Date_of_Registration: text = "Date of Registration"
        case FieldTypes.ft_Resident_From: text = "Resident From"
        case FieldTypes.ft_Resident_Until: text = "Resident Until"
        case FieldTypes.ft_Authority_Code: text = "Authority Code"
        case FieldTypes.ft_Place_of_Birth_Area: text = "Place of Birth Area"
        case FieldTypes.ft_Place_of_Birth_StateCode: text = "Place of Birth StateCode"
        case FieldTypes.ft_Address_Street: text = "Address Street"
        case FieldTypes.ft_Address_City: text = "Address City"
        case FieldTypes.ft_Address_Jurisdiction_Code: text = "Address Jurisdiction Code"
        case FieldTypes.ft_Address_Postal_Code: text = "Address Postal Code"
        case FieldTypes.ft_Document_Number_CheckDigit: text = "Document Number CheckDigit"
        case FieldTypes.ft_Date_of_Birth_CheckDigit: text = "Date of Birth CheckDigit"
        case FieldTypes.ft_Date_of_Expiry_CheckDigit: text = "Date of Expiry CheckDigit"
        case FieldTypes.ft_Personal_Number_CheckDigit: text = "Personal Number CheckDigit"
        case FieldTypes.ft_FinalCheckDigit: text = "Final CheckDigit"
        case FieldTypes.ft_Passport_Number_CheckDigit: text = "Passport Number CheckDigit"
        case FieldTypes.ft_Invitation_Number_CheckDigit: text = "Invitation Number CheckDigit"
        case FieldTypes.ft_Visa_ID_CheckDigit: text = "Visa ID CheckDigit"
        case FieldTypes.ft_Surname_And_Given_Names_CheckDigit: text = "Surname And Given Names CheckDigit"
        case FieldTypes.ft_Visa_Valid_Until_CheckDigit: text = "Visa Valid Until CheckDigit"
        case FieldTypes.ft_Permit_DL_Class: text = "Permit DL Class"
        case FieldTypes.ft_Permit_Date_of_Expiry: text = "Permit Date of Expiry"
        case FieldTypes.ft_Permit_Identifier: text = "Permit Identifier"
        case FieldTypes.ft_Permit_Date_of_Issue: text = "Permit Date of Issue"
        case FieldTypes.ft_Permit_Restriction_Code: text = "Permit Restriction Code"
        case FieldTypes.ft_Permit_Endorsed: text = "Permit Endorsed"
        case FieldTypes.ft_Issue_Timestamp: text = "Issue Timestamp"
        case FieldTypes.ft_Number_of_Duplicates: text = "Number of Duplicates"
        case FieldTypes.ft_Medical_Indicator_Codes: text = "Medical Indicator Codes"
        case FieldTypes.ft_Non_Resident_Indicator: text = "Non Resident Indicator"
        case FieldTypes.ft_Visa_Type: text = "Visa Type"
        case FieldTypes.ft_Visa_Valid_From: text = "Visa Valid From"
        case FieldTypes.ft_Visa_Valid_Until: text = "Visa Valid Until"
        case FieldTypes.ft_Duration_of_Stay: text = "Duration of Stay"
        case FieldTypes.ft_Number_of_Entries: text = "Number of Entries"
        case FieldTypes.ft_Day: text = "Day"
        case FieldTypes.ft_Month: text = "Month"
        case FieldTypes.ft_Year: text = "Year"
        case FieldTypes.ft_Unique_Customer_Identifier: text = "Unique Customer Identifier"
        case FieldTypes.ft_Commercial_Vehicle_Codes: text = "Commercial Vehicle Codes"
        case FieldTypes.ft_AKA_Date_of_Birth: text = "AKA Date of Birth"
        case FieldTypes.ft_AKA_Social_Security_Number: text = "AKA Social Security Number"
        case FieldTypes.ft_AKA_Surname: text = "AKA Surname"
        case FieldTypes.ft_AKA_Given_Names: text = "AKA Given Names"
        case FieldTypes.ft_AKA_Name_Suffix: text = "AKA Name Suffix"
        case FieldTypes.ft_AKA_Name_Prefix: text = "AKA Name Prefix"
        case FieldTypes.ft_Mailing_Address_Street: text = "Mailing Address Street"
        case FieldTypes.ft_Mailing_Address_City: text = "Mailing Address City"
        case FieldTypes.ft_Mailing_Address_Jurisdiction_Code: text = "Mailing Address Jurisdiction Code"
        case FieldTypes.ft_Mailing_Address_Postal_Code: text = "Mailing Address Postal Code"
        case FieldTypes.ft_Audit_Information: text = "Audit Information"
        case FieldTypes.ft_Inventory_Number: text = "Inventory Number"
        case FieldTypes.ft_Race_Ethnicity: text = "Race Ethnicity"
        case FieldTypes.ft_Jurisdiction_Vehicle_Class: text = "Jurisdiction Vehicle Class"
        case FieldTypes.ft_Jurisdiction_Endorsement_Code: text = "Jurisdiction Endorsement Code"
        case FieldTypes.ft_Jurisdiction_Restriction_Code: text = "Jurisdiction Restriction Code"
        case FieldTypes.ft_Family_Name: text = "Family Name"
        case FieldTypes.ft_Given_Names_RUS: text = "Given Names RUS"
        case FieldTypes.ft_Visa_ID_RUS: text = "Visa ID RUS"
        case FieldTypes.ft_Fathers_Name: text = "Fathers Name"
        case FieldTypes.ft_Fathers_Name_RUS: text = "Fathers Name RUS"
        case FieldTypes.ft_Surname_And_Given_Names_RUS: text = "Surname And Given Names RUS"
        case FieldTypes.ft_Place_Of_Birth_RUS: text = "Place Of Birth RUS"
        case FieldTypes.ft_Authority_RUS: text = "Authority RUS"
        case FieldTypes.ft_Issuing_State_Code_Numeric: text = "Issuing State Code Numeric"
        case FieldTypes.ft_Nationality_Code_Numeric: text = "Nationality Code Numeric"
        case FieldTypes.ft_Engine_Power: text = "Engine Power"
        case FieldTypes.ft_Engine_Volume: text = "Engine Volume"
        case FieldTypes.ft_Chassis_Number: text = "Chassis Number"
        case FieldTypes.ft_Engine_Number: text = "Engine Number"
        case FieldTypes.ft_Engine_Model: text = "Engine Model"
        case FieldTypes.ft_Vehicle_Category: text = "Vehicle Category"
        case FieldTypes.ft_Identity_Card_Number: text = "Identity Card Number"
        case FieldTypes.ft_Control_No: text = "Control No"
        case FieldTypes.ft_Parrent_s_Given_Names: text = "Parrent s Given Names"
        case FieldTypes.ft_Second_Surname: text = "Second Surname"
        case FieldTypes.ft_Middle_Name: text = "Middle Name"
        case FieldTypes.ft_RegCert_VIN: text = "RegCert VIN"
        case FieldTypes.ft_RegCert_VIN_CheckDigit: text = "RegCert VIN CheckDigit"
        case FieldTypes.ft_RegCert_VIN_Checksum: text = "RegCert VIN Checksum"
        case FieldTypes.ft_Line1_CheckDigit: text = "Line1 CheckDigit"
        case FieldTypes.ft_Line2_CheckDigit: text = "Line2 CheckDigit"
        case FieldTypes.ft_Line3_CheckDigit: text = "Line3 CheckDigit"
        case FieldTypes.ft_Line1_Checksum: text = "Line1 Checksum"
        case FieldTypes.ft_Line2_Checksum: text = "Line2 Checksum"
        case FieldTypes.ft_Line3_Checksum: text = "Line3 Checksum"
        case FieldTypes.ft_RegCert_RegNumber_CheckDigit: text = "RegCert RegNumber CheckDigit"
        case FieldTypes.ft_RegCert_RegNumber_Checksum: text = "RegCert RegNumber Checksum"
        case FieldTypes.ft_RegCert_Vehicle_ITS_Code: text = "RegCert Vehicle ITS Code"
        case FieldTypes.ft_Card_Access_Number: text = "Card Access Number"
        case FieldTypes.ft_Marital_Status: text = "Marital Status"
        case FieldTypes.ft_Company_Name: text = "Company Name"
        case FieldTypes.ft_Special_Notes: text = "Special Notes"
        case FieldTypes.ft_Surname_of_Spose: text = "Surname of Spose"
        case FieldTypes.ft_Tracking_Number: text = "Tracking Number"
        case FieldTypes.ft_Booklet_Number: text = "Booklet Number"
        case FieldTypes.ft_Children: text = "Children"
        case FieldTypes.ft_Copy: text = "Copy"
        case FieldTypes.ft_Serial_Number: text = "Serial Number"
        case FieldTypes.ft_Dossier_Number: text = "Dossier Number"
        case FieldTypes.ft_AKA_Surname_And_Given_Names: text = "AKA Surname And Given Names"
        case FieldTypes.ft_Territorial_Validity: text = "Territorial Validity"
        case FieldTypes.ft_MRZ_Strings_With_Correct_CheckSums: text = "MRZ Strings With Correct CheckSums"
        case FieldTypes.ft_DL_CDL_Restriction_Code: text = "DL CDL Restriction Code"
        case FieldTypes.ft_DL_Under_18_Date: text = "DL Under 18 Date"
        case FieldTypes.ft_DL_Record_Created: text = "DL Record Created"
        case FieldTypes.ft_DL_Duplicate_Date: text = "DL Duplicate Date"
        case FieldTypes.ft_DL_Iss_Type: text = "DL Iss Type"
        case FieldTypes.ft_Military_Book_Number: text = "Military Book Number"
        case FieldTypes.ft_Destination: text = "Destination"
        case FieldTypes.ft_Blood_Group: text = "Blood Group"
        case FieldTypes.ft_Sequence_Number: text = "Sequence Number"
        case FieldTypes.ft_RegCert_BodyType: text = "RegCert BodyType"
        case FieldTypes.ft_RegCert_CarMark: text = "RegCert CarMark"
        case FieldTypes.ft_Transaction_Number: text = "Transaction Number"
        case FieldTypes.ft_Age: text = "Age"
        case FieldTypes.ft_Folio_Number: text = "Folio Number"
        case FieldTypes.ft_Voter_Key: text = "Voter Key"
        case FieldTypes.ft_Address_Municipality: text = "Address Municipality"
        case FieldTypes.ft_Address_Location: text = "Address Location"
        case FieldTypes.ft_Section: text = "Section"
        case FieldTypes.ft_OCR_Number: text = "OCR Number"
        case FieldTypes.ft_Federal_Elections: text = "Federal Elections"
        case FieldTypes.ft_Reference_Number: text = "Reference Number"
        case FieldTypes.ft_Optional_Data_Checksum: text = "Optional Data Checksum"
        case FieldTypes.ft_Optional_Data_CheckDigit: text = "Optional Data CheckDigit"
        case FieldTypes.ft_Visa_Number: text = "Visa Number"
        case FieldTypes.ft_Visa_Number_Checksum: text = "Visa Number Checksum"
        case FieldTypes.ft_Visa_Number_CheckDigit: text = "Visa Number CheckDigit"
        case FieldTypes.ft_Voter: text = "Voter"
        case FieldTypes.ft_Previous_Type: text = "Previous Type"
        case FieldTypes.ft_FieldFromMRZ: text = "FieldFromMRZ"
        case FieldTypes.ft_CurrentDate: text = "CurrentDate"
        case FieldTypes.ft_Status_Date_of_Expiry: text = "Status Date of Expiry"
        case FieldTypes.ft_Banknote_Number: text = "Banknote Number"
        case FieldTypes.ft_CSC_Code: text = "CSC Code"
        case FieldTypes.ft_Artistic_Name: text = "Artistic Name"
        case FieldTypes.ft_Academic_Title: text = "Academic Title"
        case FieldTypes.ft_Address_Country: text = "Address Country"
        case FieldTypes.ft_Address_Zipcode: text = "Address Zipcode"
        case FieldTypes.ft_eID_Residence_Permit1: text = "eID Residence Permit1"
        case FieldTypes.ft_eID_Residence_Permit2: text = "eID Residence Permit2"
        case FieldTypes.ft_eID_PlaceOfBirth_Street: text = "eID PlaceOfBirth Street"
        case FieldTypes.ft_eID_PlaceOfBirth_City: text = "eID PlaceOfBirth City"
        case FieldTypes.ft_eID_PlaceOfBirth_State: text = "eID PlaceOfBirth State"
        case FieldTypes.ft_eID_PlaceOfBirth_Country: text = "eID PlaceOfBirth Country"
        case FieldTypes.ft_eID_PlaceOfBirth_Zipcode: text = "eID PlaceOfBirth Zipcode"
        case FieldTypes.ft_CDL_Class: text = "CDL Class"
        case FieldTypes.ft_DL_Under_19_Date: text = "DL Under 19 Date"
        case FieldTypes.ft_Weight_pounds: text = "Weight pounds"
        case FieldTypes.ft_Limited_Duration_Document_Indicator: text = "Limited Duration Document Indicator"
        case FieldTypes.ft_Endorsement_Expiration_Date: text = "Endorsement Expiration Date"
        case FieldTypes.ft_Revision_Date: text = "Revision Date"
        case FieldTypes.ft_Compliance_Type: text = "Compliance Type"
        case FieldTypes.ft_Family_name_truncation: text = "Family name truncation"
        case FieldTypes.ft_First_name_truncation: text = "First name truncation"
        case FieldTypes.ft_Middle_name_truncation: text = "Middle name truncation"
        case FieldTypes.ft_Exam_Date: text = "Exam Date"
        case FieldTypes.ft_Organization: text = "Organization"
        case FieldTypes.ft_Department: text = "Department"
        case FieldTypes.ft_Pay_Grade: text = "Pay Grade"
        case FieldTypes.ft_Rank: text = "Rank"
        case FieldTypes.ft_Benefits_Number: text = "Benefits Number"
        case FieldTypes.ft_Sponsor_Service: text = "Sponsor Service"
        case FieldTypes.ft_Sponsor_Status: text = "Sponsor Status"
        case FieldTypes.ft_Sponsor: text = "Sponsor"
        case FieldTypes.ft_Relationship: text = "Relationship"
        case FieldTypes.ft_USCIS: text = "USCIS"
        case FieldTypes.ft_Category: text = "Category"
        case FieldTypes.ft_Conditions: text = "Conditions"
        case FieldTypes.ft_Identifier: text = "Identifier"
        case FieldTypes.ft_Configuration: text = "Configuration"
        case FieldTypes.ft_Discretionary_data: text = "Discretionary data"
        case FieldTypes.ft_Line1_Optional_Data: text = "Line1 Optional Data"
        case FieldTypes.ft_Line2_Optional_Data: text = "Line2 Optional Data"
        case FieldTypes.ft_Line3_Optional_Data: text = "Line3 Optional Data"
        case FieldTypes.ft_EQV_Code: text = "EQV Code"
        case FieldTypes.ft_ALT_Code: text = "ALT Code"
        case FieldTypes.ft_Binary_Code: text = "Binary Code"
        case FieldTypes.ft_Pseudo_Code: text = "Pseudo Code"
        case FieldTypes.ft_Fee: text = "Fee"
        case FieldTypes.ft_Stamp_Number: text = "Stamp Number"
        case FieldTypes.ft_GNIB_Number: text = "GNIB Number"
        case FieldTypes.ft_Dept_Number: text = "Dept Number"
        case FieldTypes.ft_Telex_Code: text = "Telex Code"
        case FieldTypes.ft_Allergies: text = "Allergies"
        case FieldTypes.ft_Sp_Code: text = "Sp Code"
        case FieldTypes.ft_Court_Code: text = "Court Code"
        case FieldTypes.ft_Cty: text = "Cty"
        case FieldTypes.ft_Sponsor_SSN: text = "Sponsor SSN"
        case FieldTypes.ft_DoD_Number: text = "DoD Number"
        case FieldTypes.ft_MC_Novice_Date: text = "MC Novice Date"
        case FieldTypes.ft_DUF_Number: text = "DUF Number"
        case FieldTypes.ft_AGY: text = "AGY"
        case FieldTypes.ft_PNR_Code: text = "PNR Code"
        case FieldTypes.ft_From_Airport_Code: text = "From Airport Code"
        case FieldTypes.ft_To_Airport_Code: text = "To Airport Code"
        case FieldTypes.ft_Flight_Number: text = "Flight Number"
        case FieldTypes.ft_Date_of_Flight: text = "Date of Flight"
        case FieldTypes.ft_Seat_Number: text = "Seat Number"
        case FieldTypes.ft_Date_of_Issue_Boarding_Pass: text = "Date of Issue Boarding Pass"
        case FieldTypes.ft_CCW_Until: text = "CCW Until"
        case FieldTypes.ft_Reference_Number_Checksum: text = "Reference Number Checksum"
        case FieldTypes.ft_Reference_Number_CheckDigit: text = "Reference Number CheckDigit"
        case FieldTypes.ft_Room_Number: text = "Room Number"
        case FieldTypes.ft_Religion: text = "Religion"
        case FieldTypes.ft_RemainderTerm: text = "RemainderTerm"
        case FieldTypes.ft_Electronic_Ticket_Indicator: text = "Electronic Ticket Indicator"
        case FieldTypes.ft_Compartment_Code: text = "Compartment Code"
        case FieldTypes.ft_CheckIn_Sequence_Number: text = "CheckIn Sequence Number"
        case FieldTypes.ft_Airline_Designator_of_boarding_pass_issuer: text = "Airline Designator of boarding pass issuer"
        case FieldTypes.ft_Airline_Numeric_Code: text = "Airline Numeric Code"
        case FieldTypes.ft_Ticket_Number: text = "Ticket Number"
        case FieldTypes.ft_Frequent_Flyer_Airline_Designator: text = "Frequent Flyer Airline Designator"
        case FieldTypes.ft_Frequent_Flyer_Number: text = "Frequent Flyer Number"
        case FieldTypes.ft_Free_Baggage_Allowance: text = "Free Baggage Allowance"
        case FieldTypes.ft_PDF417Codec: text = "PDF417Codec"
        case FieldTypes.ft_Identity_Card_Number_Checksum: text = "Identity Card Number Checksum"
        case FieldTypes.ft_Identity_Card_Number_CheckDigit: text = "Identity Card Number CheckDigit"
        case FieldTypes.ft_Veteran: text = "Veteran"
        case FieldTypes.ft_DLClassCode_A1_From: text = "DLClassCode A1 From"
        case FieldTypes.ft_DLClassCode_A1_To: text = "DLClassCode A1 To"
        case FieldTypes.ft_DLClassCode_A1_Notes: text = "DLClassCode A1 Notes"
        case FieldTypes.ft_DLClassCode_A_From: text = "DLClassCode A From"
        case FieldTypes.ft_DLClassCode_A_To: text = "DLClassCode A To"
        case FieldTypes.ft_DLClassCode_A_Notes: text = "DLClassCode A Notes"
        case FieldTypes.ft_DLClassCode_B_From: text = "DLClassCode B From"
        case FieldTypes.ft_DLClassCode_B_To: text = "DLClassCode B To"
        case FieldTypes.ft_DLClassCode_B_Notes: text = "DLClassCode B Notes"
        case FieldTypes.ft_DLClassCode_C1_From: text = "DLClassCode C1 From"
        case FieldTypes.ft_DLClassCode_C1_To: text = "DLClassCode C1 To"
        case FieldTypes.ft_DLClassCode_C1_Notes: text = "DLClassCode C1 Notes"
        case FieldTypes.ft_DLClassCode_C_From: text = "DLClassCode C From"
        case FieldTypes.ft_DLClassCode_C_To: text = "DLClassCode C To"
        case FieldTypes.ft_DLClassCode_C_Notes: text = "DLClassCode C Notes"
        case FieldTypes.ft_DLClassCode_D1_From: text = "DLClassCode D1 From"
        case FieldTypes.ft_DLClassCode_D1_To: text = "DLClassCode D1 To"
        case FieldTypes.ft_DLClassCode_D1_Notes: text = "DLClassCode D1 Notes"
        case FieldTypes.ft_DLClassCode_D_From: text = "DLClassCode D From"
        case FieldTypes.ft_DLClassCode_D_To: text = "DLClassCode D To"
        case FieldTypes.ft_DLClassCode_D_Notes: text = "DLClassCode D Notes"
        case FieldTypes.ft_DLClassCode_BE_From: text = "DLClassCode BE From"
        case FieldTypes.ft_DLClassCode_BE_To: text = "DLClassCode BE To"
        case FieldTypes.ft_DLClassCode_BE_Notes: text = "DLClassCode BE Notes"
        case FieldTypes.ft_DLClassCode_C1E_From: text = "DLClassCode C1E From"
        case FieldTypes.ft_DLClassCode_C1E_To: text = "DLClassCode C1E To"
        case FieldTypes.ft_DLClassCode_C1E_Notes: text = "DLClassCode C1E Notes"
        case FieldTypes.ft_DLClassCode_CE_From: text = "DLClassCode CE From"
        case FieldTypes.ft_DLClassCode_CE_To: text = "DLClassCode CE To"
        case FieldTypes.ft_DLClassCode_CE_Notes: text = "DLClassCode CE Notes"
        case FieldTypes.ft_DLClassCode_D1E_From: text = "DLClassCode D1E From"
        case FieldTypes.ft_DLClassCode_D1E_To: text = "DLClassCode D1E To"
        case FieldTypes.ft_DLClassCode_D1E_Notes: text = "DLClassCode D1E Notes"
        case FieldTypes.ft_DLClassCode_DE_From: text = "DLClassCode DE From"
        case FieldTypes.ft_DLClassCode_DE_To: text = "DLClassCode DE To"
        case FieldTypes.ft_DLClassCode_DE_Notes: text = "DLClassCode DE Notes"
        case FieldTypes.ft_DLClassCode_M_From: text = "DLClassCode M From"
        case FieldTypes.ft_DLClassCode_M_To: text = "DLClassCode M To"
        case FieldTypes.ft_DLClassCode_M_Notes: text = "DLClassCode M Notes"
        case FieldTypes.ft_DLClassCode_L_From: text = "DLClassCode L From"
        case FieldTypes.ft_DLClassCode_L_To: text = "DLClassCode L To"
        case FieldTypes.ft_DLClassCode_L_Notes: text = "DLClassCode L Notes"
        case FieldTypes.ft_DLClassCode_T_From: text = "DLClassCode T From"
        case FieldTypes.ft_DLClassCode_T_To: text = "DLClassCode T To"
        case FieldTypes.ft_DLClassCode_T_Notes: text = "DLClassCode T Notes"
        case FieldTypes.ft_DLClassCode_AM_From: text = "DLClassCode AM From"
        case FieldTypes.ft_DLClassCode_AM_To: text = "DLClassCode AM To"
        case FieldTypes.ft_DLClassCode_AM_Notes: text = "DLClassCode AM Notes"
        case FieldTypes.ft_DLClassCode_A2_From: text = "DLClassCode A2 From"
        case FieldTypes.ft_DLClassCode_A2_To: text = "DLClassCode A2 To"
        case FieldTypes.ft_DLClassCode_A2_Notes: text = "DLClassCode A2 Notes"
        case FieldTypes.ft_DLClassCode_B1_From: text = "DLClassCode B1 From"
        case FieldTypes.ft_DLClassCode_B1_To: text = "DLClassCode B1 To"
        case FieldTypes.ft_DLClassCode_B1_Notes: text = "DLClassCode B1 Notes"
        case FieldTypes.ft_Surname_at_Birth: text = "Surname at Birth"
        case FieldTypes.ft_Civil_Status: text = "Civil Status"
        case FieldTypes.ft_Number_of_Seats: text = "Number of Seats"
        case FieldTypes.ft_Number_of_Standing_Places: text = "Number of Standing Places"
        case FieldTypes.ft_Max_Speed: text = "Max Speed"
        case FieldTypes.ft_Fuel_Type: text = "Fuel Type"
        case FieldTypes.ft_EC_Environmental_Type: text = "EC Environmental Type"
        case FieldTypes.ft_Power_Weight_Ratio: text = "Power Weight Ratio"
        case FieldTypes.ft_Max_Mass_of_Trailer_Braked: text = "Max Mass of Trailer Braked"
        case FieldTypes.ft_Max_Mass_of_Trailer_Unbraked: text = "Max Mass of Trailer Unbraked"
        case FieldTypes.ft_Transmission_Type: text = "Transmission Type"
        case FieldTypes.ft_Trailer_Hitch: text = "Trailer Hitch"
        case FieldTypes.ft_Accompanied_by: text = "Accompanied by"
        case FieldTypes.ft_Police_District: text = "Police District"
        case FieldTypes.ft_First_Issue_Date: text = "First Issue Date"
        case FieldTypes.ft_Payload_Capacity: text = "Payload Capacity"
        case FieldTypes.ft_Number_of_Axels: text = "Number of Axels"
        case FieldTypes.ft_Permissible_Axle_Load: text = "Permissible Axle Load"
        case FieldTypes.ft_Precinct: text = "Precinct"
        case FieldTypes.ft_Invited_by: text = "Invited by"
        case FieldTypes.ft_Purpose_of_Entry: text = "Purpose of Entry"
        case FieldTypes.ft_Skin_Color: text = "Skin Color"
        case FieldTypes.ft_Complexion: text = "Complexion"
        case FieldTypes.ft_Airport_From: text = "Airport From"
        case FieldTypes.ft_Airport_To: text = "Airport To"
        case FieldTypes.ft_Airline_Name: text = "Airline Name"
        case FieldTypes.ft_Airline_Name_Frequent_Flyer: text = "Airline Name Frequent Flyer"
        case FieldTypes.ft_In_Tanks: text = "In Tanks"
        case FieldTypes.ft_Exept_In_Tanks: text = "Exept In Tanks"
        }
        return text
        
    }
}